config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("admin/", admin.site.urls),
    path("menus/", include("dinedash.menu.urls")),
]

dinedash/menu/urls.py
"""
Url paths for the Menu app
These endpoints are accessed from <domain>/menus/<pattern>
"""
from django.urls import path

from . import views

app_name = "menu"
urlpatterns = [
    path("", views.MenuList.as_view(), name="list"),
    path("create", views.MenuCreate.as_view(), name="create"),
    path("<pk>", views.MenuDetail.as_view(), name="detail"),
    path("<pk>/delete", views.MenuDelete.as_view(), name="delete"),
    path("<pk>/update", views.MenuUpdate.as_view(), name="update"),
    path("<str:menu_pk>/category/create", views.MenuCategoryCreate.as_view(), name='create_category'),
    path("<str:menu_pk>/category/<pk>/delete", views.MenuCategoryDelete.as_view(), name='delete_category'),
    path("<str:menu_pk>/category/<pk>/update", views.MenuCategoryUpdate.as_view(), name='update_category'),
]

dinedash/menu/models.py
"""
This module defines the data structure of a Menu.
"""
from django.db import models

from .fields import ShortUUIDField


class Menu(models.Model):
    """
    Describes a menu with many categories and items
    eg. Breakfast Menu, Lunch Menu, Weekend Menu
    """

    uuid = ShortUUIDField(primary_key=True, editable=False)
    title = models.CharField(max_length=150)
    description = models.TextField()

    class Meta:
        ordering = ["title"]

    def __str__(self):
        return str(self.title)


class MenuCategory(models.Model):
    """
    A section of a menu that has many menu items
    eg. Entrees, Sides, Dessert
    """

    title = models.CharField(max_length=150)
    description = models.TextField()
    menu = models.ForeignKey(to=Menu, null=False, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return str(self.title)


class MenuItem(models.Model):
    """
    Describes an item belonging to a Menu
    eg. Burger, Quesadilla, Pad Thai
    """

    title = models.CharField(max_length=150)
    description = models.TextField()
    category = models.ForeignKey(
        to=MenuCategory,
        null=False,
        on_delete=models.CASCADE,
    )
    price = models.DecimalField(max_digits=9, decimal_places=2)

    def __str__(self):
        return str(self.title)


class AddonSection(models.Model):
    """
    A section of addons
    eg. Choice of Side, Size, Spiciness
    """

    title = models.CharField(max_length=150)
    description = models.TextField()
    required = models.BooleanField()
    menu_item = models.ForeignKey(to=MenuItem,
                                  null=False,
                                  on_delete=models.CASCADE)

    def __str__(self):
        return str(self.title)


class Addon(models.Model):
    """
    Describes additional options for a menu item
    eg. Extra Salsa, Side of Fries, Toasted
    """

    SELECTION_TYPES = [
        ("R", "Radio"),
        ("M", "Multiple Selection"),
    ]

    description = models.CharField(max_length=150)
    selection = models.CharField(max_length=1,
                                 choices=SELECTION_TYPES,
                                 default=SELECTION_TYPES[0][0])
    section = models.ForeignKey(
        to=AddonSection,
        null=False,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return str(self.description)

dinedash/menu/views.py
"""
Views for accessing and changing the Menu models
"""
from django.urls import reverse, reverse_lazy
from django.forms.models import inlineformset_factory
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .models import Menu, MenuCategory


class MenuList(ListView):
    """Shows a list of all the menus available"""

    model = Menu
    paginate_by = 15
    template_name = "menu/list.html"


class MenuDetail(DetailView):
    """Shows a full Menu as if a customer was reading it"""

    model = Menu
    template_name = "menu/detail.html"


class MenuCreate(CreateView):
    """Allows creation of Menu models"""

    model = Menu
    template_name = "menu/create.html"
    fields = ['title', 'description']

    def get_success_url(self):
        return reverse('menu:detail', kwargs={'pk': self.object.uuid})


class MenuDelete(DeleteView):
    """Allows deletion of Menu models"""

    model = Menu
    template_name = "menu/delete.html"
    success_url = reverse_lazy('menu:list')


class MenuUpdate(UpdateView):
    """Allows updating of Menu models"""

    model = Menu
    template_name = "menu/update.html"
    fields = ['title', 'description']

    def get_success_url(self):
        return reverse('menu:detail', kwargs={'pk': self.object.uuid})


class MenuCategoryCreate(CreateView):
    """Allows creation of categories"""

    model = MenuCategory
    template_name = "menu/create-category.html"
    fields = ['title', 'description']

    def get_parent_menu(self):
        return Menu.objects.get(uuid=self.kwargs['menu_pk'])

    def get_queryset(self):
        return super().get_queryset().filter(menu=self.get_parent_menu())

    def get_success_url(self):
        return reverse('menu:detail', kwargs={'pk': self.get_parent_menu().uuid}) + f'#{self.object.title}'

    def form_valid(self, form):
        form.instance.menu = self.get_parent_menu()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = self.get_parent_menu()
        return context


class MenuCategoryDelete(DeleteView):
    """Allows deletion of categories"""

    model = MenuCategory

    def get_parent_menu(self):
        return Menu.objects.get(uuid=self.kwargs['menu_pk'])

    def get_success_url(self):
        return reverse('menu:detail', kwargs={'pk': self.get_parent_menu().uuid}) + f'#{self.object.title}'

    def get_queryset(self):
        return super().get_queryset().filter(menu=self.get_parent_menu())

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class MenuCategoryUpdate(UpdateView):
    """Allows updating of categories"""

    model = MenuCategory
    template_name = "menu/update-category.html"
    fields = ['title', 'description']

    def get_success_url(self):
        return reverse('menu:detail', kwargs={'pk': self.object.uuid})

    def get_parent_menu(self):
        return Menu.objects.get(uuid=self.kwargs['menu_pk'])

    def get_success_url(self):
        return reverse('menu:detail', kwargs={'pk': self.get_parent_menu().uuid}) + f'#{self.object.title}'

    def get_queryset(self):
        return super().get_queryset().filter(menu=self.get_parent_menu())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = self.get_parent_menu()
        return context

dinedash/menu/templates/menu/create-category.html
{% extends "menu/detail.html" %}
{% load crispy_forms_tags %}

{% block menu_controls %}
{# Clear the menu controls while editing Categories #}
{% endblock menu_controls %}

{% block category_controls %}
<form method="post">{% csrf_token %}
  <h3 id="new-category">New Category</h3>
  {{ form | crispy }}
  <div class="btn-group" role="group" aria-label="Menu controls">
    <button type="submit" class="btn btn-primary">Create</button>
    <a class="btn btn-secondary" href="{% url 'menu:detail' pk=menu.uuid %}">Cancel</a>
  </div>
</form>
{% endblock category_controls %}

dinedash/menu/templates/menu/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create Menu{% endblock %}

{% block body %}
<form method="post">{% csrf_token %}
  {{ form | crispy }}
  <button type="submit" class="btn btn-primary">Create</button>
  <a href="{% url 'menu:list' %}">
    <button type="button" class="btn btn-secondary">Cancel</button>
  </a>
</form>
{% endblock body %}

dinedash/menu/templates/menu/delete.html
{% extends "base.html" %}

{% block title %}
Delete {{ object.title }}
{% endblock title %}

{% block body %}
<form method="post">{% csrf_token %}
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <div class="btn-group" role="group" aria-label="Menu controls">
    <a class="btn btn-secondary" href="{% url 'menu:detail' pk=object.uuid %}">Cancel</a>
    <button type="submit" class="btn btn-danger">Confirm Delete</button>
  </div>
</form>
{% endblock  %}

dinedash/menu/templates/menu/detail.html
{% extends "base.html" %}

{% block title %}{{ menu }}{% endblock title %}

{% block body %}
<a href="{% url 'menu:list' %}">&laquo; Back to all menus</a>

{% block menu_controls %}
<div class="btn-group float-right" role="group" aria-label="Menu controls">
  <a href="{% url 'menu:update' pk=menu.uuid %}" type="button" class="btn btn-primary">Modify</a>
  <a href="{% url 'menu:delete' pk=menu.uuid %}" type="button" class="btn btn-danger">Delete</a>
</div>
{% endblock menu_controls %}

{% block menu_meta %}
<h1 class="display-4">{{ menu.title }}</h1>
<p class="lead">
  {{ menu.description }}
</p>
{% endblock menu_meta %}

<ul class="list-group my-4">
  {% for category in menu.menucategory_set.all %}
  <li class="list-group-item p-4">
    {% if object.id != category.id %}
      <h3 class="d-inline" id="{{ category.title }}">{{ category.title }}</h3>
      <a href="{% url 'menu:update_category' menu_pk=menu.uuid pk=category.pk %}#{{ category.title }}" type="button">Edit</a>
      <span> | </span>
      <a href="{% url 'menu:delete_category' menu_pk=menu.uuid pk=category.pk %}" class="text-danger" type="button">Delete</a>
      <p>{{ category.description }}</p>
    {% else %}
      {% block update_category %}
      {% endblock update_category %}
    {% endif %}
    <table class="table table-borderless table-hover">
      <tbody>
        {% for item in category.menuitem_set.all %}
        <tr>
          <td>
            <span class="font-weight-bold">{{ item.title }}</span>
            <span class="float-right">${{ item.price }}</span>
            <br>
            <span class="font-weight-light">{{ item.description }}</span>
          </td>
        </tr>
        {% endfor %}
        <tr>
          <td>
            <small><a href="#" class="text-small">+ Add new item</a></small>
          </td>
        </tr>
      </tbody>
    </table>
  </li>
  {% endfor %}
  <li class="list-group-item p-4">
    {% block category_controls %}
    <a href="{% url 'menu:create_category' menu_pk=menu.uuid %}#new-category" type="button">Create New Category</a>
    {% endblock category_controls %}
  </li>
</ul>
{% endblock body %}

dinedash/menu/templates/menu/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Menus{% endblock %}

{% block body %}
<div class="modal" id="exampleModal" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <img src="{% static 'qr-code.svg' %}" style="padding:2rem" width="100%" alt="QR"/>
        <p>A placeholder until we can generate real QR codes for menus.</p>
      </div>
    </div>
  </div>
</div>

<a href="{% url 'menu:create' %}">
  <button type="button" class="btn btn-primary">Create</button>
</a>

<table class="table mt-3">
  <thead>
    <tr>
      <th scope="col">QR</th>
      <th scope="col">Menu Title</th>
      <th scope="col">Menu Description</th>
    </tr>
  </thead>
  <tbody>
  {% for menu in object_list %}
    <tr>
      <td>
        <button type="button" class="btn btn-light btn-sm" data-toggle="modal" data-target="#exampleModal">
          <img src="{% static 'qr-code.svg' %}" height="12px" width="12px" alt="QR"/>
        </button>
      </td>
      <th scope="row">
        <a href="{% url 'menu:detail' pk=menu.uuid %}">{{ menu.title }}</a>
      </th>
      <td>{{ menu.description }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock body %}

dinedash/menu/templates/menu/update-category.html
{% extends "menu/detail.html" %}
{% load crispy_forms_tags %}

{% block menu_controls %}
{# Clear the menu controls while editing Categories #}
{% endblock menu_controls %}

{% block update_category %}
<form method="post" id="{{ category.title }}">{% csrf_token %}
  {{ form | crispy }}
  <div class="btn-group" role="group" aria-label="Menu controls">
    <button type="submit" class="btn btn-primary">Update</button>
    <a class="btn btn-secondary" href="{% url 'menu:detail' pk=menu.uuid %}">Cancel</a>
  </div>
</form>
{% endblock update_category %}

dinedash/menu/templates/menu/update.html
{% extends "menu/detail.html" %}
{% load crispy_forms_tags %}

{% block title %}Edit {{ object }}{% endblock %}

{% block menu_headers %}
<form class="mb-3" method="post">{% csrf_token %}
  {{ form | crispy }}
  <div class="btn-group" role="group" aria-label="Menu controls">
    <button type="submit" class="btn btn-primary">Update</button>
    <a class="btn btn-secondary" href="{% url 'menu:detail' pk=object.uuid %}">Cancel</a>
  </div>
</form>
{% endblock menu_headers %}

dinedash/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width" />
    <title>
      {% block title %}{% endblock title %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    {% block head %}
    {% endblock head %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
      <a class="navbar-brand" href="{% url 'menu:list' %}">DineDash</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'menu:list' %}">Menus</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body %}
      {% endblock body %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

dinedash/templates/pages/home.html
{% extends "base.html" %}